services:
  postgres:
    image: postgres:16
    container_name: acme-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5445
      POSTGRES_DB: main
    ports:
      # Host port 5445 : Container port 5432
      # Left side (5445) is the port on your host machine
      # Right side (5432) is the port inside the container
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d main -p 5445"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
